from __future__ import annotations

from app.core.schemas import ResearchReport


def to_json(report: ResearchReport) -> str:
    return report.model_dump_json(indent=2)


def to_markdown(report: ResearchReport) -> str:
    cfg = report.config
    lines: list[str] = []

    lines.append(f"# TrendLens — {cfg.domain}")
    lines.append("")

    meta = [f"**Time window:** last {cfg.time_window_days} days"]
    if cfg.competitors:
        meta.append(f"**Competitors tracked:** {', '.join(cfg.competitors)}")
    if cfg.target_users:
        meta.append(f"**Target users:** {cfg.target_users}")
    if cfg.geographic_market:
        meta.append(f"**Market:** {cfg.geographic_market}")
    lines.extend(meta)
    lines.append("")
    lines.append("---")
    lines.append("")

    for i, item in enumerate(report.items, 1):
        conf_emoji = {"High": "🟢", "Medium": "🟡", "Low": "🔴"}.get(item.confidence, "⚪")
        lines.append(f"## {i}. {item.headline}")
        lines.append("")
        lines.append(f"{conf_emoji} **Confidence:** {item.confidence}")
        lines.append("")
        lines.append(f"**What happened:** {item.what_happened}")
        lines.append("")
        lines.append(f"**Why it matters:** {item.why_it_matters}")
        lines.append("")

        if item.podcast_evidence:
            lines.append("**Podcast signals:**")
            for e in item.podcast_evidence:
                lines.append(f"- [{e.text}]({e.url})" if e.url else f"- {e.text}")
            lines.append("")

        if item.reddit_evidence:
            lines.append("**Reddit signals:**")
            for e in item.reddit_evidence:
                lines.append(f"- [{e.text}]({e.url})" if e.url else f"- {e.text}")
            lines.append("")

        if item.source_links:
            lines.append("**Sources:**")
            for link in item.source_links:
                lines.append(f"- {link}")
            lines.append("")

        lines.append(f"**→ PM action:** {item.pm_action}")
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append(f"*Generated by TrendLens · {report.generated_at}*")
    return "\n".join(lines)
